"""password and image moved to userstats

Revision ID: 72633b8d5c32
Revises: 0763d677d453
Create Date: 2026-04-16 14:05:32.542345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72633b8d5c32'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('genero', sa.String(length=20), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('genero')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    op.drop_table('user_stats')
    # ### end Alembic commands ###
